{{- if .Values.semaphore.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "semaphore.serviceAccountName" . }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
  {{- with .Values.semaphore.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
